### ISSUE TITLE
Set up Kanban boards React Group Capstone

### ISSUE THREAD

**Issue by jlcarrascof** [jlcarrascof/Space-Travelers-Hub#25]
This is the [link](https://github.com/jlcarrascof/Space-Travelers-Hub/issues) of our Kanban boards
    Numbers of students in our team
        student A : **@mohamedgamaleldin999999** 
        student B : **@jlcarrascof**

**Comment by rica213** [comment]
# 🟢 STATUS: APPROVED
Hi Mohamed,
Hi Javier,
My name is Larissa. I am your code reviewer 🥰

Your Kanban is well set up. Every task is shared equally 🛸 🛸 
This milestone is complete.
I wish you a great week of collaboration, and that you will find solutions to any obstacles. Good luck ❤️ 
Congratulations! 🎉 

<img src="https://media3.giphy.com/media/W5ZUxqXT1lmiysXsDE/giphy.gif"/>

## Highlights

- [ ] No Linters errors ✔️ 
- [ ] Descriptive PR ✔️ 
- [ ] Correct Github flow ✔️ 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you consider them as they can improve your code. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by jlcarrascof** [comment]
Hi, dear Larissa **@rica213** Nice to see you again, my friend.

Thanks for your good vibes, we'll do our best :-)
